"""Write the web dashboard's color tokens from reconix/theme.py (the single source).

    python scripts/export_tokens.py        # → web/src/styles/tokens.css

Light values go on :root, dark values on [data-theme="dark"] (set by the theme toggle)
and under prefers-color-scheme for the moment before the toggle's script runs.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reconix.theme import WEB_TOKENS  # noqa: E402

OUT = ROOT / "web" / "src" / "styles" / "tokens.css"


def block(values: dict, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--{name}: {value};" for name, value in values.items())


def main() -> None:
    css = (
        "/* GENERATED by scripts/export_tokens.py from reconix/theme.py. Do not edit. */\n"
        f":root {{\n{block(WEB_TOKENS['light'])}\n  color-scheme: light;\n}}\n"
        "@media (prefers-color-scheme: dark) {\n"
        f"  :root:not([data-theme=\"light\"]) {{\n{block(WEB_TOKENS['dark'], '    ')}\n"
        "    color-scheme: dark;\n  }\n}\n"
        f":root[data-theme=\"dark\"] {{\n{block(WEB_TOKENS['dark'])}\n  color-scheme: dark;\n}}\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
